services:
  mongodb:
    image: mongo:6.0
    container_name: veloop_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: veloop_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/veloop_wallet_demo
      - JWT_SECRET=veloop_super_secret_jwt_key_2026_demo_secure!
      - JWT_EXPIRES_IN=7d
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: veloop_frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo_data:
