/**
 * VELoop Rewards System Constants & Enums
 */

const CURRENCIES = {
  VES: 'VEs',
  SVES: 'SVEs',
  GEMS: 'Gems',
  TOKENS: 'Tokens',
  SPINS: 'Spins'
};

const TRANSACTION_TYPES = {
  CREDIT: 'CREDIT',
  DEBIT: 'DEBIT'
};

const TRANSACTION_SOURCES = {
  // Credits
  REWARD: 'REWARD',
  BONUS: 'BONUS',
  REFERRAL: 'REFERRAL',
  DAILY_REWARD: 'DAILY_REWARD',
  AD_REWARD: 'AD_REWARD',
  GAME_REWARD: 'GAME_REWARD',
  ADMIN_CREDIT: 'ADMIN_CREDIT',
  EXCHANGE_CREDIT: 'EXCHANGE_CREDIT',
  WITHDRAWAL_REFUND: 'WITHDRAWAL_REFUND',
  // Debits
  WITHDRAWAL: 'WITHDRAWAL',
  EXCHANGE_DEBIT: 'EXCHANGE_DEBIT',
  ADMIN_DEBIT: 'ADMIN_DEBIT',
  CORRECTION: 'CORRECTION'
};

const TRANSACTION_STATUS = {
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  PENDING: 'PENDING'
};

const WITHDRAWAL_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED'
};

const PAYOUT_METHODS = {
  UPI: 'UPI',
  PAYPAL: 'PAYPAL',
  AMAZON_GIFT_CARD: 'AMAZON_GIFT_CARD',
  GOOGLE_PLAY_GIFT_CARD: 'GOOGLE_PLAY_GIFT_CARD'
};

const USER_ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN'
};

const ACCOUNT_STATUS = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  FLAGGED: 'FLAGGED'
};

const AUDIT_ACTIONS = {
  WITHDRAWAL_CREATED: 'WITHDRAWAL_CREATED',
  WITHDRAWAL_APPROVED: 'WITHDRAWAL_APPROVED',
  WITHDRAWAL_REJECTED: 'WITHDRAWAL_REJECTED',
  WALLET_CREDIT: 'WALLET_CREDIT',
  WALLET_DEBIT: 'WALLET_DEBIT',
  BALANCE_CORRECTION: 'BALANCE_CORRECTION',
  PAYOUT_CONFIG_CHANGED: 'PAYOUT_CONFIG_CHANGED',
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN: 'USER_LOGIN'
};

module.exports = {
  CURRENCIES,
  TRANSACTION_TYPES,
  TRANSACTION_SOURCES,
  TRANSACTION_STATUS,
  WITHDRAWAL_STATUS,
  PAYOUT_METHODS,
  USER_ROLES,
  ACCOUNT_STATUS,
  AUDIT_ACTIONS
};
